{
 "title": "Kubecost-genticmesh",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ingress",
    "query": "label_values(nginx_ingress_controller_requests, ingress) "
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Mesh CPU Cost",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (\n  (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"mesh\"} or node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"nginx\"})\n * on(node) group_left() node_cpu_hourly_cost \n)"
    }
   ]
  },
  {
   "title": "Mesh Memory Cost",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (\n  (container_memory_working_set_bytes{namespace=\"mesh\"} or container_memory_working_set_bytes{pod=~\"nginx\"}) / 1024 / 1024 / 1024\n * on(node) group_left() node_ram_hourly_cost \n)"
    }
   ]
  },
  {
   "title": "Mesh Cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # Memory\n   sum by(pod) (\n    (container_memory_working_set_bytes{namespace=\"mesh\"} or container_memory_working_set_bytes{pod=~\"nginx\"}) / 1024 / 1024 / 1024\n     * on(node) group_left() node_ram_hourly_cost\n   ) + \n   # CPU\n   sum by(pod) (\n    (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"mesh\"} or node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"nginx\"})\n     * on(node) group_left() node_cpu_hourly_cost\n   )\n)\n",
     "legendFormat": "Mesh Total Cost"
    }
   ]
  },
  {
   "title": "Average request handling time by path",
   "type": "graph",
   "description": "The average response time for each API path.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "msec" }
   ],
   "targets": [
    {
     "expr": "sum by (path)(\n  rate(\n    nginx_ingress_controller_request_duration_seconds_sum{ingress =~ \"$ingress\"}[1m]\n  )\n)\n/\nsum by (path)(\n  rate(\n    nginx_ingress_controller_request_duration_seconds_count{ingress =~ \"$ingress\"}[1m]\n  )\n)\n* 1000",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Cost Efficiency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 / \n  (sum by (path)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_sum{ingress =~ \"$ingress\"}[1m]\n    )\n  )\n  /\n  sum by (path)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_count{ingress =~ \"$ingress\"}[1m]\n    )\n  )\n  * 1000\n  )\n)\n/\nignoring(path) group_left\nsum(\n  # Memory\n   sum by(pod) (\n    (container_memory_working_set_bytes{namespace=\"mesh\"} or container_memory_working_set_bytes{pod=~\"nginx\"}) / 1024 / 1024 / 1024\n     * on(node) group_left() node_ram_hourly_cost\n   ) + \n   # CPU\n   sum by(pod) (\n    (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"mesh\"} or node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"nginx\"})\n     * on(node) group_left() node_cpu_hourly_cost\n   ) \n)\n"
    }
   ]
  }
 ]
}